SELECT 
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
    
FROM DEVELOPERS D

JOIN (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
) S ON D.SKILL_CODE & S.CODE > 0

GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME

ORDER BY D.ID;
